<h1>Pending</h1>
<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>#</th>
				<th>Instrument</th>
				<th>Quantity</th>
				<th>Price</th>
				<th>Side</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>1</td>
				<td>AAPL</td>
				<td>3</td>
				<td>10</td>
				<td>BUY</td>
				<td></td>
			</tr>
			<tr>
				<td>2</td>
				<td>WALM</td>
				<td>10</td>
				<td>16</td>
				<td>BUY</td>
				<td></td>
			</tr>
			<tr>
				<td>3</td>
				<td>GREN</td>
				<td>12</td>
				<td>100</td>
				<td>BUY</td>
				<td></td>
			</tr>
		</tbody>
	</table>
</div>